title: The Spyder Girl
description: Nuestro proyecto para el certamen de proyectos libres de la OSL.
author: Geek & Tech Girls
logo: /static/img/avatar.png
github: https://github.com/geekandtechgirls
about: Extracting information from our social media.

baseurl: ""
url: "https://geekandtechgirls.github.io/The-Spyder-Girl"


share:
  twitter_username: geekandtechgirl


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
